
language: python
python:
  - "3.8"

# command to install dependencies
install:
  - pip install -r requirements.txt

script:
  - python -m unittest tests/test*
  - coverage run --omit */venv/* main.py -m unittest tests/test*
  - coveralls