"""uuid change

Revision ID: c2bb9a942346
Revises: 7bf836968dbd
Create Date: 2021-05-19 21:07:50.548508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2bb9a942346'
down_revision = '7bf836968dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uuid', table_name='department')
    op.drop_column('department', 'long_name')
    op.drop_column('department', 'uuid')
    op.drop_index('uuid', table_name='employee')
    op.drop_column('employee', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('uuid', mysql.VARCHAR(length=36), nullable=False))
    op.create_index('uuid', 'employee', ['uuid'], unique=False)
    op.add_column('department', sa.Column('uuid', mysql.VARCHAR(length=36), nullable=False))
    op.add_column('department', sa.Column('long_name', mysql.VARCHAR(length=200), nullable=False))
    op.create_index('uuid', 'department', ['uuid'], unique=False)
    # ### end Alembic commands ###
