"""empty message

Revision ID: f5edcd610cac
Revises: c2bb9a942346
Create Date: 2021-05-20 13:30:38.066257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5edcd610cac'
down_revision = 'c2bb9a942346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('uuid', sa.String(length=36), nullable=False))
    op.add_column('department', sa.Column('long_name', sa.String(length=200), nullable=False))
    op.create_unique_constraint(None, 'department', ['uuid'])
    op.add_column('employee', sa.Column('uuid', sa.String(length=36), nullable=False))
    op.create_unique_constraint(None, 'employee', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='unique')
    op.drop_column('employee', 'uuid')
    op.drop_constraint(None, 'department', type_='unique')
    op.drop_column('department', 'long_name')
    op.drop_column('department', 'uuid')
    # ### end Alembic commands ###
